full_name: 'Resume'
description: 'This is a template for a standard Resume'
author: 'Rukmal Weerawarana'
required_input:
    - 'full_name'
    - 'address_line_1'
    - 'address_city_state'
    - 'address_zip'
    - 'address_country'
    - 'phone'
    - 'email'
    - 'website'
    - 'linkedin'
    - 'last_updated'
    - 'max_description_priority'
required_classes:
    - 'Degree'
    - 'WorkExperience'
    - 'Publication'
    - 'Talk'
    - 'KnowledgeArea'
    - 'SkillGroup'
    - 'Project'
    - 'Award'
    - 'Certification'
    - 'ActivityType'
