name: precis
channels:
  - defaults
dependencies:
  - astroid=2.2.5
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - isort=4.3.15
  - lazy-object-proxy=1.3.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - mccabe=0.6.1
  - ncurses=6.1
  - openssl=1.1.1b
  - pip=19.0.3
  - pylint=2.3.1
  - python=3.7.2
  - python.app=2
  - readline=7.0
  - setuptools=40.8.0
  - sqlite=3.27.2
  - tk=8.6.8
  - wheel=0.33.1
  - wrapt=1.11.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - cycler==0.10.0
    - decorator==4.4.0
    - isodate==0.6.0
    - kiwisolver==1.0.1
    - matplotlib==3.0.3
    - networkx==2.2
    - numpy==1.16.2
    - owlready2==0.14
    - pyparsing==2.3.1
    - python-dateutil==2.8.0
    - rdflib==4.2.2
    - six==1.12.0

