name: Build test artifacts

on: [pull_request]

jobs:
  build_sample_artifacts:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Precis from setup.py
        run: python setup.py install
      - name: Build sample artifacts
        working-directory: scripts/
        run: |
          python build_sample_rdf.py
          python build_sample_cv.py
      - name: Install LaTeX
        run: sudo apt-get --assume-yes install texlive-full
      - name: Compile sample PDFs
        working-directory: data/
        run: |
          pdflatex cv.tex
      - name: Save artifacts for review
        uses: actions/upload-artifact@v2
        with:
          name: sample-resources
          path: |
            data/sample.rdf
            data/cv.tex
            data/cv.pdf
