name: Commit built sample artifacts

on:
  push:
    branches:
      - master
      - main


jobs:
  build_commit_sample_artifacts:
    uses: rukmal/precis/.github/workflows/build_sample_artifacts.yml@master
  commit_sample_artifacts:
    needs: build_sample_artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download all sample artifacts
        uses: actions/download-artifact@v2
        with:
          name: sample-resources
          path: data/
      - name: Display added files
        run: git add . && git status
      - name: Commit sample artifacts to Pull Request
        uses: EndBug/add-and-commit@v7 # See: https://github.com/marketplace/actions/add-commit
        with:
          add: "data"
          default_author: github_actions
          commit_message: "[GitHub Actions] Commit sample artifacts"
